include(CheckIncludeFile)
include(CheckIncludeFiles)
include(CheckFunctionExists)
include(CheckSymbolExists)
include(TestBigEndian)
include(CheckLibraryExists)
include(CheckTypeSize)


test_big_endian(WORDS_BIGENDIAN)

if(WORDS_BIGENDIAN)
    set(GMX_INTEGER_BIG_ENDIAN 1)
endif(WORDS_BIGENDIAN)
check_function_exists(vprintf HAVE_VPRINTF)
if (NOT HAVE_VPRINTF)
	check_function_exists(_doprnt HAVE_DOPRNT)
endif()
check_function_exists(exit HAVE_EXIT)
check_function_exists(fseeko HAVE_FSEEKO)
check_function_exists(mkstemp HAVE_MKSTEMP)
check_function_exists(remove HAVE_REMOVE)
check_function_exists(sqrt HAVE_SQRT)
check_function_exists(strcasecmp HAVE_STRCASECMP)
check_function_exists(strdup HAVE_STRDUP)


check_include_file("inttypes.h" HAVE_INTTYPES_H)
check_include_file("memory.h" HAVE_MEMORY_H)
check_include_file("rpc/rpc.h" HAVE_RPC_RPC_H)
check_include_files("rpc/types.h;rpc/xdr.h" HAVE_RPC_XDR_H)
check_include_file("stdint.h" HAVE_STDINT_H)
check_include_file("stdlib.h" HAVE_STDLIB_H)
check_include_file("stdbool.h" HAVE_STDBOOL_H)
check_include_file("string.h" HAVE_STRING_H)
check_include_file("sys/stat.h" HAVE_SYS_STAT_H)
check_include_file("sys/types.h" HAVE_SYS_TYPES_H)
check_include_file("unistd.h" HAVE_UNISTD_H)
check_include_files("stdlib.h;stdarg.h;string.h;float.h" STDC_HEADERS)
check_type_size("int" SIZEOF_INT)
check_type_size("long int" SIZEOF_LONG_INT)
check_type_size("long long int" SIZEOF_LONG_LONG_INT)

configure_file(config.h.cmake config.h)
